### ISSUE TITLE
Signature always returning empty true

### ISSUE THREAD

**Issue by ian-sayles** [warting/android-signaturepad#206]
**Describe the bug**
Since upgrading from 0.0.21 to 0.1.0 when checking for if the signature is empty it is always returning true, even if the signature as been signed.

The code that always returns true:
if (viewModel.signaturePadAdapter?.isEmpty == true) {

**Smartphone (please complete the following information):**
 - Device: Sony H8416
 - OS: Android 10
 - Library Version 0.1.0

**Comment by warting** [comment]
Hey @ian-sayles
This should be fixed in https://github.com/warting/android-signaturepad/pull/207
