### ISSUE TITLE
Update properties after view has being created

### ISSUE THREAD

**Issue by GuilhE** [warting/android-signaturepad#53]
**Is your feature request related to a problem? Please describe.**

After the view has been created I can't change the following properties:
```
this.setMinWidth(penMinWidth.value)
this.setMaxWidth(penMaxWidth.value)
this.setPenColor(penColor.toArgb())
this.setVelocityFilterWeight(velocityFilterWeight)
this.setClearOnDoubleClick(clearOnDoubleClick)
```

**Describe the solution you'd like**

> The `update` block can be run multiple times (on the UI thread as well) due to recomposition, and it is the right place to set `View` properties depending on state. When state changes, the block will be re-executed to set the new properties. Note the block will also be ran once right after the `factory` block completes

So instead of the porperties being changed inside `factory`, I believe they should be changed inside `update`

**Describe alternatives you've considered**
I believe there's none.

**Comment by warting** [comment]
Thank you @GuilhE! Good catch. Your changes has been released in v0.0.15.
