### ISSUE TITLE
[Warning] - Default value for clearOnDoubleClick

### ISSUE THREAD

**Issue by GuilhE** [warting/android-signaturepad#57]
I was reading your [README.md](https://github.com/warting/android-signaturepad/blob/main/README.md) and you state:

> clearOnDoubleClick - Double click to clear pad (default: false)

caution because in your wrapper it's `true` by default:
https://github.com/warting/android-signaturepad/blob/155030c8d2cfe155a0a3061bc742e1389464232a/signature-pad/src/main/java/se/warting/signaturepad/SignaturePadView.kt#L24

Although it's true for the `View`:
https://github.com/warting/android-signaturepad/blob/155030c8d2cfe155a0a3061bc742e1389464232a/signature-view/src/main/java/se/warting/signatureview/views/SignaturePad.kt#L61

Anyway, thanks for this lib it's is very handy and the best I used so far 😉

**Comment by warting** [comment]
Thank you! Fixed in v.0.0.16.
